p8105\_hw2\_xw2598
================
Xinyao Wu
2018-10-02

problem1
--------

``` r
library(tidyverse)
```

    ## -- Attaching packages ---------------------------------------------------------- tidyverse 1.2.1 --

    ## √ ggplot2 3.0.0     √ purrr   0.2.5
    ## √ tibble  1.4.2     √ dplyr   0.7.6
    ## √ tidyr   0.8.1     √ stringr 1.3.1
    ## √ readr   1.1.1     √ forcats 0.3.0

    ## -- Conflicts ------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
nyc_data = read.csv("./data files/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")%>% 
  #data clean
janitor::clean_names() %>% 
  #retain specific variables 
select(line:entry,vending,ada) %>% 
  #convert the variable entry from character to logic
 #gather(key="routes_served", value = "route_value",route1:route11 ) %>% 
mutate(
     entry=as.character(entry),
     entry = replace(entry,entry =="YES", "TRUE"),
       entry =replace(entry,entry =="NO","FALSE"),
       entry = as.logical(entry)
)
```

``` r
#new dataset variables
names(nyc_data) 
```

    ##  [1] "line"              "station_name"      "station_latitude" 
    ##  [4] "station_longitude" "route1"            "route2"           
    ##  [7] "route3"            "route4"            "route5"           
    ## [10] "route6"            "route7"            "route8"           
    ## [13] "route9"            "route10"           "route11"          
    ## [16] "entrance_type"     "entry"             "vending"          
    ## [19] "ada"

``` r
#The dimension of the resulting dataset
print("rows:")
```

    ## [1] "rows:"

``` r
nrow(nyc_data)
```

    ## [1] 1868

``` r
print("columns:")
```

    ## [1] "columns:"

``` r
ncol(nyc_data)
```

    ## [1] 19

This dataset contains variables: line,station name,station latitude,station longitude,route1,route2,route3,route4,route5,route6,route7,route8,route9,route10,route11,entrance type,entry,vending,ada. My data cleaning steps: 1.Change the variables names. 2.Select the specific variables according to the requirement. 3.Change the type of the data in "entry". The dimension of the resulting dataset is 1868 rows \* 19 columns.These data is not tidy enough, I suggest to gather all of the routes into one variable so I put related codes in the comment lines.

``` r
##The number of distinct stations:
#select the variables that can identify stations
n_station = select(nyc_data,line,station_name,ada) %>% 
distinct()
nrow(n_station)
```

    ## [1] 465

``` r
##The number of stations that are ADA compliant
ada_compliant = filter(n_station, ada=="TRUE") 
  nrow(ada_compliant)
```

    ## [1] 84

``` r
##The proportion of station entrances / exits without vending allow entrance
nrow(filter(nyc_data,vending=="NO",entry=="TRUE"))/nrow(filter(nyc_data,vending=="NO"))
```

    ## [1] 0.3770492

There are 465 distinct stations, and there are 84 stations that are ADA compliant.The proportion of station entrances / exits without vending allow entrance is 0.377.

``` r
#Reformat data so that route number and route name are distinct variables
new_nyc_data = nyc_data %>% 
gather(key="route_name", value = "route_number",route1:route11 ) %>% 
#Number of Dinstinct stations that serve the A train
select(line,station_name, route_name, route_number,ada) %>% 
  #filte A train
  filter(route_number == "A") 
```

    ## Warning: attributes are not identical across measure variables;
    ## they will be dropped

``` r
  #count distinct station serving A train
  A_station = distinct(new_nyc_data,line,station_name,.keep_all = TRUE) 
  nrow(A_station)
```

    ## [1] 60

``` r
# carculate number  of  ADA compliant in stations serving A train
  nrow(filter(A_station,ada=="TRUE"))
```

    ## [1] 17

``` r
# carculate proportion of  ADA compliant in stations serving A train
  nrow(filter(A_station,ada=="TRUE"))/nrow(A_station)
```

    ## [1] 0.2833333

60 distinct stations that serve the A train Of the stations that serve the A train, the number of ada compliant stations serving A train is , and the proportion of ADA compliant is 0.283.

problem 2
---------
